[package]
name = "vib-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true


[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
serde.workspace = true
serde_json.workspace = true

serde_derive = "1.0.217" # for doctest
