[package]
name = "example-plugin"
version = "0.1.0"
edition = "2021"


[lib]
name = "test"
crate-type = ["rlib", "cdylib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
vib-api.workspace = true
