[package]
name = "silverblue-package"
version = "0.1.0"
edition = "2021"

[lib]
name = "plugin"
crate-type = ["rlib", "cdylib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
vib-common.workspace = true
